name: RDP via Cloudflare (No Auth)

on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Download cloudflared
        run: |
          Invoke-WebRequest https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-windows-amd64.exe -OutFile cloudflared.exe

      - name: Enable RDP and create user
        run: |
          net user rdpuser RdpPassword123 /add
          net localgroup administrators rdpuser /add
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name 'fDenyTSConnections' -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - name: Start Cloudflare Tunnel without auth
        run: |
          .\cloudflared.exe tunnel --url tcp://localhost:3389
