name: RDP over Cloudflare

on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:

    - name: إنشاء مستخدم RDP
      run: |
        net user rdpuser RdpPass123 /add /Y
        net localgroup administrators rdpuser /add
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name 'fDenyTSConnections' -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - name: تنزيل cloudflared
      run: |
        Invoke-WebRequest https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-windows-amd64.exe -OutFile cloudflared.exe

    - name: تشغيل نفق Cloudflare المؤقت (Quick Tunnel)
      run: |
        Start-Process -NoNewWindow -FilePath ".\cloudflared.exe" -ArgumentList "tunnel --url tcp://localhost:3389"
        Start-Sleep -Seconds 10
        Get-Process cloudflared

    - name: إبقاء الجلسة مفتوحة لمدة 6 ساعات
      run: |
        Start-Sleep -Seconds 21600
